version: "3.8"

services:
  db:
    image: mysql:8.3.0
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"

  adminer:
    image: adminer:4.8.1
    ports:
      - 8080:8080

volumes:
  database:
